---
## https://github.com/MISP/misp-modules

- stat: path={{ mispmodules_rootdir }}/misp-modules
  register: mm
- name: git clone MISP modules
  git: repo=https://github.com/MISP/misp-modules.git
       dest={{ mispmodules_rootdir }}/misp-modules
  when: not mm.stat.exists

- name: debian | install dependencies for MISP modules (pip3)
  pip: requirements={{ mispmodules_rootdir }}/misp-modules/REQUIREMENTS executable=pip3
  when: ansible_os_family == 'Debian'
## centos7: pip points to python34
- name: redhat | install dependencies for MISP modules (pip3)
  pip: requirements={{ mispmodules_rootdir }}/misp-modules/REQUIREMENTS executable=pip
  when: ansible_os_family == 'RedHat'

- name: install MISP modules (pip3)
  pip: name=file://{{ mispmodules_rootdir }}/misp-modules executable=pip3

- name: add MISP modules script for boot
  lineinfile:
    dest: /etc/rc.local
    regexp: "sudo -H -u www-data misp-modules .* &"
    line: "sudo -H -u www-data misp-modules -s > /tmp/misp-modules.boot 2>&1 &"
    insertbefore: "^exit 0"
    backup: yes

- name: check if misp modules is running
  shell: "ps axu | egrep '[m]isp-modules'"
  register: ps
  changed_when: false
  ignore_errors: true

# https://github.com/ansible/ansible/issues/16052
# https://docs.ansible.com/ansible/latest/intro_configuration.html#allow-world-readable-tmpfiles
# https://github.com/ansible/ansible/issues/26741
- name: start MISP modules app
  shell: "misp-modules -s > /tmp/misp-modules.start 2>&1 &"
  args:
    executable: /bin/sh
  become: yes
  become_user: www-data
  when: "'misp-modules' not in ps.stdout"

