---

- include: travis.yml

- name: install testing tools
  package: name={{ item }} state=present
  with_items: "{{ misp_testing_pkg }}"

- name: replace misp.local hostname
  replace: dest="{{ item }}" regexp='http:\/\/misp.local' replace="{{ misp_base_url }}" backup=yes
  with_items:
    - "{{ misp_rootdir }}/tests/curl_tests.sh"
- name: check tool version for debugging
  command: "{{ item }}"
  with_items:
    - php --version
    - composer --version
  changed_when: false
  ignore_errors: true
- name: pip dependencies for testing
  pip: name={{ item }} executable=pip3
  with_items:
    - coveralls
    - codecov
    - nose
    - requests-mock

- name: ensure test user in group of web server
  user: "user={{ misp_testing_user }} groups={{ www_user }} append=yes"
  become: yes

- name: check home permissions
  file: dest={{ item }} mode=0755 state=directory
  with_items:
    - "{{ misp_testing_user_home }}/build"
    - "{{ misp_testing_user_home }}"
    - /home

   # Get authkey
- name: check world-writeable permissions
  file: "dest={{ item }} mode=0777 owner={{ misp_testing_user }} recurse=yes"
  with_items:
    - "{{ misp_rootdir }}/build"
    - "{{ misp_rootdir }}/tests"
- name: use MISP travis bootstrap
  copy: "src={{ misp_rootdir }}/travis/bootstrap.php dest={{ misp_rootdir }}/app/Config/bootstrap.php backup=yes force=yes"

- include: misp-key-file.yml

- name: MISP tree permissions
## break .gnupg if applied to whole tree
#  file: "dest={{ misp_rootdir }} owner={{ www_user }} mode=755 recurse=yes"
  file: "dest={{ misp_rootdir }} owner={{ www_user }} mode=755"
  become: yes
- name: MISP tree permissions
  file: "dest={{ item }} owner={{ www_user }} mode=755 recurse=yes"
## Note: recurse is only valid if directory and can't select them from fileglob
#  with_fileglob:
#    - "{{ misp_rootdir }}/*"
## Not doing root files, build/tests/PyMISP addressed in their own tasks, INSTALL/travis ignored
  with_items:
    - "{{ misp_rootdir }}/app"
    - "{{ misp_rootdir }}/format"
    - "{{ misp_rootdir }}/tools"
  become: yes
- name: PyMISP world-writeable permissions
  file: "dest={{ misp_rootdir }}/PyMISP mode=777 owner={{ misp_testing_user }} recurse=yes"
  become: yes
## FIXME! for some reason .coverage still own by root during serverspec test
- name: PyMISP .coverage permissions
  file: "dest={{ misp_rootdir }}/PyMISP/.coverage mode=777 owner={{ misp_testing_user }} state=touch"
- name: PyMISP pymisp.egg-info permissions
  file: "dest={{ misp_rootdir }}/PyMISP/pymisp.egg-info mode=777 owner={{ misp_testing_user }} state=directory recurse=yes"

- debug: var=misp_base_url
- debug: var=userInit
- name: set local variables in PyMISP/tests/keys.py
  lineinfile:
    dest: "{{ misp_rootdir }}/PyMISP/tests/keys.py"
    regexp: "{{ item.re }}"
    line: "{{ item.l }}"
    create: yes
    owner: "{{ misp_testing_user }}"
  with_items:
    - { re: "^misp_url = .*", l: "misp_url = \"{{ misp_base_url }}\"" }
    - { re: "^misp_key = .*", l: "misp_key = \"{{ userkey }}\"" }
    - { re: '^misp_verifycert = .*', l: "misp_verifycert = {{ misp_pymisp_verifycert }}" }
  no_log: true
- name: symlink key file in examples/events
  file: "src={{ misp_rootdir }}/PyMISP/tests/keys.py dest={{ misp_rootdir }}/PyMISP/examples/events/keys.py state=link force=yes owner={{ misp_testing_user }}"
- name: symlink key file in PyMISP
  file: "src={{ misp_rootdir }}/PyMISP/tests/keys.py dest={{ misp_rootdir }}/PyMISP/keys.py state=link force=yes owner={{ misp_testing_user }}"

